import React from 'react';

export const resultColumns = [
  {
    Header: '',
    accessor: 'statName',
    style: { fontWeight: 'bold', textAlign: 'left' },
    sortable: false,
    resizable: false,
  },
  {
    Header: 'Home',
    accessor: 'home',
    width: 60,
    style: { backgroundColor: '#d32f2f', color: '#fff', fontWeight: 'bold' },
    sortable: false,
    resizable: false,
  },
  {
    Header: '',
    accessor: 'arrow',
    width: 30,
    style: { color: '#9a0007', fontWeight: 'bold' },
    sortable: false,
    resizable: false,
  },
  {
    Header: 'Away',
    accessor: 'away',
    width: 60,
    style: { backgroundColor: '#d32f2f', color: '#fff', fontWeight: 'bold' },
    sortable: false,
    resizable: false,
  },
];
export const playerColumns = [
  {
    Header: '',
    accessor: 'name',
    style: { backgroundColor: '#333', color: '#fff', fontWeight: 'bold' },
  },
  {
    Header: 'Apps',
    columns: [
      {
        Header: <i className="far fa-check-square" />,
        id: 'apps',
        accessor: a => Number(a.apps),
        width: 30,
        resizable: false,
        style: { fontWeight: 'bold' },
      },
      {
        Header: <div style={{ color: '#bbb' }}>%</div>,
        id: 'percentApps',
        accessor: a => Number(a.percentApps),
        width: 35,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem', verticalAlign: 'center' },
      },
      {
        Header: <i style={{ color: '#FFC300' }} className="fas fa-bullseye" />,
        id: 'appTarget',
        accessor: a => Number(a.appTarget),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
      {
        Header: <div style={{ color: '#FFC300' }}>%</div>,
        id: 'percentAppTarget',
        accessor: a => Number(a.percentAppTarget),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
    ],
  },
  {
    Header: 'Goals',
    columns: [
      {
        Header: <i className="fas fa-futbol" />,
        id: 'goals',
        accessor: a => Number(a.goals),
        width: 30,
        resizable: false,
        style: { fontWeight: 'bold' },
      },
      {
        Header: <div style={{ color: '#bbb' }}>Av</div>,
        id: 'goalsPerGame',
        accessor: a => Number(a.goalsPerGame),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
      {
        Header: <div style={{ color: '#bbb' }}>%</div>,
        id: 'percentGoals',
        accessor: a => Number(a.percentGoals),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
      {
        Header: <i style={{ color: '#FFC300' }} className="fas fa-bullseye" />,
        id: 'goalTarget',
        accessor: a => Number(a.goalTarget),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
      {
        Header: <div style={{ color: '#FFC300' }}>%</div>,
        id: 'percentGoalTarget',
        accessor: a => Number(a.percentGoalTarget),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
    ],
  },
  {
    Header: 'Assists',
    columns: [
      {
        Header: <i className="fas fa-key" />,
        id: 'assists',
        accessor: a => Number(a.assists),
        width: 30,
        resizable: false,
        style: { fontWeight: 'bold' },
      },
      {
        Header: <div style={{ color: '#bbb' }}>Av</div>,
        id: 'assistsPerGame',
        accessor: a => Number(a.assistsPerGame),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
      {
        Header: <div style={{ color: '#bbb' }}>%</div>,
        id: 'percentAssists',
        accessor: a => Number(a.percentAssists),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
      {
        Header: <i style={{ color: '#FFC300' }} className="fas fa-bullseye" />,
        id: 'assistTarget',
        accessor: a => Number(a.assistTarget),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
      {
        Header: <div style={{ color: '#FFC300' }}>%</div>,
        id: 'percentAssistTarget',
        accessor: a => Number(a.percentAssistTarget),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
    ],
  },
  {
    Header: 'MVP',
    columns: [
      {
        Header: <i className="fas fa-medal" />,
        id: 'mvp',
        accessor: a => Number(a.mvp),
        width: 30,
        resizable: false,
        style: { fontWeight: 'bold' },
      },
      {
        Header: <div style={{ color: '#bbb' }}>Av</div>,
        id: 'mvpPerGame',
        accessor: a => Number(a.mvpPerGame),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
    ],
  },
  {
    Header: 'Other',
    columns: [
      {
        Header: '% Inv.',
        id: 'goalContribution',
        accessor: a => Number(a.goalContribution),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
      {
        Header: '$',
        id: 'balance',
        accessor: a => parseFloat(a.balance).toFixed(2),
        width: 45,
        resizable: false,
        style: { opacity: '0.5', fontSize: '0.65rem' },
      },
    ],
  },
];
